// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerStatsRM;

#nullable disable

namespace PlayerStatsRM.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20260209103533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PlayerStatsRM.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Goals = 25,
                            Name = "Mbappe"
                        },
                        new
                        {
                            Id = 2,
                            Goals = 22,
                            Name = "Vinicius"
                        },
                        new
                        {
                            Id = 3,
                            Goals = 15,
                            Name = "Bellingham"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
